title: Grace Woods
description: A human that likes building things and helping people
baseurl: ""
url: "https://graciouswoodsy.github.io"

# Build settings
markdown: kramdown
theme: minima  # Using minima theme instead of primer
permalink: /blog/:year/:month/:day/:title/

# Blog settings
paginate: 5
paginate_path: "/blog/page:num/"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - README.md